name = "workers-d1-hono-drizzle-template"
compatibility_date = "2023-12-01"
node_compat = true

[vars]
JWT_SECRET = "<jwt-secret-here>"

[[d1_databases]]
binding = "DB"
database_name = "<db-name>"
database_id = "<db-id>"
